import React from 'react';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';

import './globals.css';

import localFont from 'next/font/local';
import Script from 'next/script';
import { Analytics } from '@vercel/analytics/next';

import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/components/theme-provider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontHeading = localFont({
  src: '../../public/assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
});

// TODO
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Current Datastream URL
  // https://experience.adobe.com/#/@aemonacpprodcampaign/sname:prod/data-collection/scramjet/65930925-1d0b-407e-8a86-65b60ec2e68c/
  // const datastreamId = '65930925-1d0b-407e-8a86-65b60ec2e68c';
  // const orgId = '906E3A095DC834230A495FD6@AdobeOrg';

  return (
    <html lang="en" suppressHydrationWarning>
      <Script id="config-alloy">
        {`
          !function(n,o){o.forEach(function(o){n[o]||((n.__alloyNS=n.__alloyNS||
          []).push(o),n[o]=function(){var u=arguments;return new Promise(
          function(i,l){n.setTimeout(function(){n[o].q.push([i,l,u])})})},n[o].q=[])})}
          (window,["alloy"]);
          const datastreamId = '65930925-1d0b-407e-8a86-65b60ec2e68c';
          const orgId = '906E3A095DC834230A495FD6@AdobeOrg';
          const debugEnabled = true;
          const thirdPartyCookiesEnabled = false;
          const clickCollectionEnabled = false;
          const alloyOption = { 
            datastreamId, 
            orgId, 
            debugEnabled,
            thirdPartyCookiesEnabled,
            clickCollectionEnabled,
          };
          alloy('configure', alloyOption);
        `}
      </Script>
      <Script
        src={'https://cdn1.adoberesources.net/alloy/2.22.0/alloy.min.js'}
      ></Script>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
